<?php

echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");
echo("coucou");

?>